###This notebook:
+ ktrain
+ hugging face transformers
+ roberta-base
+ lower LR 5e-5 + triangular policy
+ keep emojis -> uses emojiS library (decode function) instead of emoji (demojize)


08/07:
accuracy .74

Note: weight file has been moved into model folder - move out if it causes problems when loading predictor


###Check Requirements/imports

In [ ]:
import tensorflow as tf
print(tf.version.VERSION)

2.5.0


In [ ]:
import pandas as pd


In [ ]:
!pip3 install -U emojis

emojiS library: https://emojis.readthedocs.io/en/latest/api.html#module-emojis

emojis cheat sheet: https://www.webfx.com/tools/emoji-cheat-sheet/

In [ ]:
pip install contractions

In [ ]:
!pip3 install -q ktrain 

In [ ]:
pip install -U sklearn

In [ ]:
pip install parse_version

In [ ]:
pip install git+https://github.com/amaiya/eli5@tfkeras_0_10_1

In [ ]:
import os

import numpy as np
import pandas as pd

import tensorflow as tf
import tensorflow_hub as hub

from keras.utils import np_utils

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import matplotlib.pyplot as plt

gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    # Currently, memory growth needs to be the same across GPUs
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Memory growth must be set before GPUs have been initialized
    print(e)

print("Version: ", tf.__version__)
print("Eager mode: ", tf.executing_eagerly())
print("Hub version: ", hub.__version__)
print("GPU is", "available" if tf.config.list_physical_devices('GPU') else "NOT AVAILABLE")

1 Physical GPUs, 1 Logical GPUs
Version:  2.5.0
Eager mode:  True
Hub version:  0.12.0
GPU is available


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


###Load data

In [ ]:
# Load train data
train_path = '/content/drive/MyDrive/TeamLab/data/semeval_taskA_corrected.csv'

df_train = pd.read_csv(train_path, header=0, names=['index',
                                                    'irony_label',
                                                    'tweet'])
                                                

In [ ]:
df_train.head()

index  irony_label                                              tweet
0      1            1  Sweet United Nations video. Just in time for C...
1      2            1  @mrdahl87 We are rumored to have talked to Erv...
2      3            1  Hey there! Nice to see you Minnesota/ND Winter...
3      4            0                3 episodes left I'm dying over here
4      5            1  I can't breathe! was chosen as the most notabl...

In [ ]:
# Check if dataset is balanced

# Classes are 1 and 0. Tweet can either be ironic or non-ironic -> binary classification
classes = df_train.irony_label.unique()

print((df_train.irony_label == 0).sum())
print((df_train.irony_label == 1).sum())

# => Balanced

1923
1911


In [ ]:
# Load test data
test_path = '/content/drive/MyDrive/TeamLab/data/semeval_taskA_test.csv'

df_test = pd.read_csv(test_path, sep='\t', header=0, names=['index',
                                                            'irony_label',
                                                            'tweet'])

print((df_test.irony_label == 0).sum())
print((df_test.irony_label == 1).sum())

df_test.head()

473
311


index  irony_label                                              tweet
0      1            0  @Callisto1947 Can U Help?||More conservatives ...
1      2            1  Just walked in to #Starbucks and asked for a "...
2      3            0              #NOT GONNA WIN http://t.co/Mc9ebqjAqj
3      4            0  @mickymantell He is exactly that sort of perso...
4      5            1  So much #sarcasm at work mate 10/10 #boring 10...

In [ ]:
x_train = df_train['tweet'].to_numpy()
y_train = df_train['irony_label'].to_numpy()

x_test = df_test['tweet'].to_numpy()
y_test = df_test['irony_label'].to_numpy()

###Normalisation of input

Normalise:
+ hashtags
+ tagged users
+ emoji (+ ones that are made up of characters e.g. :P)
+ urls 
+ laugh (haha, lol..)
+ remove stops

In [ ]:
import emojis
from nltk.tokenize import TweetTokenizer
import re
import contractions
import numpy as np


def normalise_tweet(tweet):
    norm_tweet = re.sub("&", "and", tweet)
    norm_tweet = re.sub(r"[<>]", "", norm_tweet)
    norm_tweet = re.sub("http:.*", "url", norm_tweet)
    norm_tweet = re.sub("@", " @", norm_tweet)
    norm_tweet = re.sub("#", " ", norm_tweet)
    
    norm_tweet = re.sub(r"[-()/_;:{}=~|,\[\]]", " ", norm_tweet)

    norm_tweet = contractions.fix(norm_tweet)

    tokenizer = TweetTokenizer()
    tweet_tokens = tokenizer.tokenize(norm_tweet)
    final_tweet_list = []

    for token in tweet_tokens:        
        if token.startswith("@"):
            # then token is a user tag
            tag_token = "tagged_user"
            if final_tweet_list.count(tag_token) < 3:
                final_tweet_list.append(tag_token)
        elif emojis.count(token) == 1:
            # then token is an emoji
            emoji_token = emojis.decode(token)
            if final_tweet_list.count(emoji_token) < 2:
                final_tweet_list.append(emoji_token)
        else:
            final_tweet_list.append(token)
    
    final_tweet = ' '.join(final_tweet_list)
    
    return final_tweet.strip()

# check normalisation    
#return tweet_tokens, final_tweet.strip()

In [ ]:
x_train_norm = []
for tweet in x_train:
    x_train_norm.append(normalise_tweet(tweet))

x_test_norm = []
for tweet in x_test:
    x_test_norm.append(normalise_tweet(tweet))

#x_train_norm = np.array(x_train_norm)
#x_test_norm = np.array(x_test_norm)

#x_train_norm

In [ ]:
x_train_norm[10:20]

['Oh thank GOD our entire office email system is down ... the day of a big event . Santa you know JUST what to get me for xmas .',
 'But instead I am scrolling through Facebook Instagram and Twitter for hours on end accomplishing nothing .',
 'tagged_user :pout: no he bloody is not I was upstairs getting changed !',
 "Cold or warmth both suffuse one's cheeks with pink colour tone ... Do you understand the underlying difference and its texture ?",
 'Just great when you are mobile bill arrives by text',
 'crushes are great until you realize they will never be interested in you . p',
 'Buffalo sports media is smarter than all of us . Where else can you get the quality insight offered by Harrington and Busgaglia .',
 'I guess my cat also lost 3 pounds when she went to the vet after I have been feeding her a few times a day . Eating food WorkingOut',
 'tagged_user tagged_user Rosenthal trading a SP for a defense only SS ? Brilliant trade .',
 'But tagged_user was trying to find us and my ba

In [ ]:
from statistics import mean

seq_len = []

idx = 0
for tweet in x_train_norm:
    if len(tweet.split()) > 35:
        print(idx, tweet)
    seq_len.append(len(tweet.split()))
    idx += 1

print(max(seq_len))
print(mean(seq_len))

888 This time change is crazy . everyone is all up here like woohoo its 11am let us live life ! and I am like it is 5am and I have not slept at all yet .
948 Kyle it will not let me tagged_user you ? But yeah we are grown ass men with fast cars . Who gives af lol . And bring it to my room hooah ? See ya in a bit .
39
15.357329160146062


##Model (ktrain)

In [ ]:
import ktrain
from ktrain import text

from keras.callbacks import ModelCheckpoint, EarlyStopping, CSVLogger

categories = [0, 1]

MODEL_NAME = 'roberta-base'

# Transormer is a wrapper to the Hugging Face transformers library for text classification.
t = text.Transformer(MODEL_NAME, maxlen=100, class_names=categories)

# Using normalised input data
trn = t.preprocess_train(x_train_norm, y_train)
val = t.preprocess_test(x_test_norm, y_test)

model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=16)


preprocessing train...
language: en
train sequence lengths:
	mean : 15
	95percentile : 27
	99percentile : 30


Is Multi-Label? False
preprocessing test...
language: en
test sequence lengths:
	mean : 16
	95percentile : 28
	99percentile : 31


###Train

In [ ]:
# best LR found after trying several ones and also using the k-train learning rate estimator
best_lr = 5e-5

In [ ]:
# Train
# Parameters: LR, epochs
# LR==(5e-5)

learner.autofit(lr=best_lr, checkpoint_folder='/my_models', verbose=1)

# if epochs is None, then early_stopping and reduce_on_plateau are atomatically set to 6 and 3, respectively.
# if lr missing, it will be estimated (initial lr)

early_stopping automatically enabled at patience=5
reduce_on_plateau automatically enabled at patience=2


begin training using triangular learning rate policy with max lr of 5e-05...
Epoch 1/1024
240/240 [==============================] - 102s 364ms/step - loss: 0.6615 - accuracy: 0.5905 - val_loss: 0.6431 - val_accuracy: 0.6633
Epoch 2/1024
240/240 [==============================] - 88s 364ms/step - loss: 0.5729 - accuracy: 0.7089 - val_loss: 0.6078 - val_accuracy: 0.6913
Epoch 3/1024
240/240 [==============================] - 89s 366ms/step - loss: 0.4635 - accuracy: 0.7830 - val_loss: 0.6631 - val_accuracy: 0.6862
Epoch 4/1024
240/240 [==============================] - 89s 366ms/step - loss: 0.3482 - accuracy: 0.8498 - val_loss: 0.6880 - val_accuracy: 0.7015

Epoch 00004: Reducing Max LR on Plateau: new max lr will be 2.5e-05 (if not early_stopping).
Epoch 5/1024
240/240 [==============================] - 89s 366ms/step - loss: 0.1824 - accuracy: 0.9330 - val_loss: 0.7997 - val_acc

###Evaluate/Inspect model

In [ ]:
learner.validate(class_names=t.get_classes())

              precision    recall  f1-score   support

           0       0.89      0.55      0.68       473
           1       0.57      0.90      0.70       311

    accuracy                           0.69       784
   macro avg       0.73      0.73      0.69       784
weighted avg       0.77      0.69      0.69       784



array([[262, 211],
       [ 31, 280]])

In [ ]:
# Set weights to those of the best epoch
learner.model.load_weights('/my_models/weights-06.hdf5')

In [ ]:
learner.validate(class_names=t.get_classes())

              precision    recall  f1-score   support

           0       0.86      0.68      0.76       473
           1       0.63      0.83      0.71       311

    accuracy                           0.74       784
   macro avg       0.74      0.75      0.74       784
weighted avg       0.77      0.74      0.74       784



array([[322, 151],
       [ 54, 257]])

In [ ]:
# the ones that we got most wrong
learner.view_top_losses(n=10, preproc=t)

----------
id:523 | loss:6.65 | true:0 | pred:1)

----------
id:197 | loss:6.52 | true:0 | pred:1)

----------
id:204 | loss:6.4 | true:0 | pred:1)

----------
id:5 | loss:6.33 | true:0 | pred:1)

----------
id:524 | loss:6.31 | true:0 | pred:1)

----------
id:618 | loss:6.24 | true:0 | pred:1)

----------
id:217 | loss:6.24 | true:0 | pred:1)

----------
id:66 | loss:6.18 | true:1 | pred:0)

----------
id:555 | loss:6.14 | true:1 | pred:0)

----------
id:278 | loss:6.06 | true:0 | pred:1)



In [ ]:
# print out instance to see why...
print(x_test_norm[523])
print(x_test_norm[197])
print(x_test_norm[204])
print(x_test_norm[5])
print(x_test_norm[524])

print(x_test_norm[618])
print(x_test_norm[217])
print('true1,pred0', x_test_norm[66])
print('true1,pred0', x_test_norm[555])
print(x_test_norm[278])

tagged_user now to remember which book ... goodluck
Nice touch . All the bar staff in the ground wearing saintsfc t shirts
tagged_user his daughter is painting his toes ! That is a parenting WIN in my book .
Corny jokes are my absolute favorite
tagged_user Ahem ... yeah .. something like that irony is one of the few things keeping sanity when facing RU propaganda . CrazyIvan
Love it when my mans on a cleaning spree .. Saves me doing it :ok_hand: :kissing_heart: :kissing_heart:
Wow Look what the NFL Rams player who did " Hands Up do not Shoot " pose has been arrested for url
true1,pred0 Produce Mobile Apps not url
true1,pred0 Scoped out a new route on today's 5k . But oh .. the crowds the traffic the noise :smile: not ... url
good luck finding someone to take the other side of that bet LOL tagged_user


###Make predictions on new data

In [ ]:
predictor = ktrain.get_predictor(learner.model, preproc=t)

In [ ]:
test_sent = ('Cool it is raining again')

In [ ]:
predictor.predict(test_sent)

1

In [ ]:
# Ask for explanation
predictor.explain(test_sent)

In [ ]:
more_sents = ['Going to the dentist for a root canal this afternoon. Yay, I can’t wait.', 
              'It was so nice of my dad to come to my graduation party. #not', 
              'I drank a healthy, homemade fruit smoothie...in a Budweiser glass #irony', 
              'Dogs are really cute, one day I want to live in a big house with many dogs', 
              'some trees are really tall, others not so much', 
              'just came back from dinner at Nandos with my mates']

In [ ]:
predictor.predict(more_sents)

[1, 1, 1, 0, 0, 0]

In [ ]:
# Ask for explanation
predictor.explain(more_sents[0])

In [ ]:
# Ask for explanation
predictor.explain(more_sents[1])

In [ ]:
# Ask for explanation
predictor.explain(more_sents[2])

In [ ]:
# Ask for explanation
predictor.explain(more_sents[3])

In [ ]:
# Ask for explanation
predictor.explain(more_sents[4])

In [ ]:
# Ask for explanation
predictor.explain(more_sents[5])

###Save + Reload

In [ ]:
predictor.save('/my_models/ID_RoBERTa_emojis')

In [ ]:
# Reload to check that model has been saved correctly
reloaded_predictor = ktrain.load_predictor('/my_models/ID_RoBERTa_emojis')

In [ ]:
reloaded_predictor.predict(test_sent)

1

In [ ]:
# Do reloaded_predictor and original predictor give the same numbers?
reloaded_predictor.predict_proba(test_sent)

array([0.17225026, 0.8277497 ], dtype=float32)

In [ ]:
predictor.predict_proba(test_sent)

array([0.17225026, 0.8277497 ], dtype=float32)

In [ ]:
reloaded_predictor.get_classes()

[0, 1]

In [ ]:
# Copy model files to drive - files on google colab disk space are temporary and get deleted when the session is over

%cp -av "/content/my_models/ID_RoBERTa_emojis" "/content/drive/MyDrive/TeamLab/my_models"

'/content/my_models/ID_RoBERTa_emojis' -> '/content/drive/MyDrive/TeamLab/my_models/ID_RoBERTa_emojis'
'/content/my_models/ID_RoBERTa_emojis/weights-06.hdf5' -> '/content/drive/MyDrive/TeamLab/my_models/ID_RoBERTa_emojis/weights-06.hdf5'
'/content/my_models/ID_RoBERTa_emojis/weights-02.hdf5' -> '/content/drive/MyDrive/TeamLab/my_models/ID_RoBERTa_emojis/weights-02.hdf5'
'/content/my_models/ID_RoBERTa_emojis/tokenizer_config.json' -> '/content/drive/MyDrive/TeamLab/my_models/ID_RoBERTa_emojis/tokenizer_config.json'
'/content/my_models/ID_RoBERTa_emojis/tf_model.preproc' -> '/content/drive/MyDrive/TeamLab/my_models/ID_RoBERTa_emojis/tf_model.preproc'
'/content/my_models/ID_RoBERTa_emojis/merges.txt' -> '/content/drive/MyDrive/TeamLab/my_models/ID_RoBERTa_emojis/merges.txt'
'/content/my_models/ID_RoBERTa_emojis/special_tokens_map.json' -> '/content/drive/MyDrive/TeamLab/my_models/ID_RoBERTa_emojis/special_tokens_map.json'
'/content/my_models/ID_RoBERTa_emojis/config.json' -> '/content/dri


To load and continue training
```
# save model and Preprocessor instance after partially training
ktrain.get_predictor(model, preproc).save('/tmp/my_predictor')

# reload Predictor and extract model
model = ktrain.load_predictor('/tmp/my_predictor').model

# re-instantiate Learner and continue training
learner = ktrain.get_learner(model, train_data=trn, val_data=val)
learner.fit_onecycle(2e-5, 1)
```

